repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 2.1.3
    hooks:
      - id: poetry-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: files
      - id: end-of-file-fixer
        exclude: files
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [ ports, lib, yag, tests ]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: [ ports, lib, yag, tests ]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: flake8
        args: [ --config, lint/.flake8 ]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args: [ --config=lint/.gitlint, --msg-filename ]
  - repo: https://github.com/pycqa/pylint
    rev: v3.3.8
    hooks:
      - id: pylint
        args:
          [
            --rcfile=lint/pylintrc,
            --output-format=colorized,
          ]
        files: "^(ports/|lib/|yag/).*"
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [
  #         types-dateparser,
  #         types-requests
  #       ]
  #       exclude: tests/
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.6
  #   hooks:
  #     - id: bandit
  #       args: [
  #           --exclude, tests
  #       ]
