from pathlib import (
    PureWindowsPath,
)

SYSTEM_DRIVE_LETTER = "C"
APP_DRIVE_LETTER = "D"
FIRST_CD_DRIVE_LETTER = "E"
SECOND_CD_DRIVE_LETTER = "F"
THIRD_CD_DRIVE_LETTER = "G"
FOURTH_CD_DRIVE_LETTER = "H"
FIFTH_CD_DRIVE_LETTER = "H"

SYSTEM_DRIVE = PureWindowsPath(f"{SYSTEM_DRIVE_LETTER}:\\")
APP_DRIVE = PureWindowsPath(f"{APP_DRIVE_LETTER}:\\")
FIRST_CD_DRIVE = PureWindowsPath(f"{FIRST_CD_DRIVE_LETTER}:\\")
SECOND_CD_DRIVE = PureWindowsPath(f"{SECOND_CD_DRIVE_LETTER}:\\")
THIRD_CD_DRIVE = PureWindowsPath(f"{THIRD_CD_DRIVE_LETTER}:\\")
FOURTH_CD_DRIVE = PureWindowsPath(f"{FOURTH_CD_DRIVE_LETTER}:\\")
FIFTH_CD_DRIVE = PureWindowsPath(f"{FIFTH_CD_DRIVE_LETTER}:\\")

APP_DIR = APP_DRIVE / "APP"
